In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# Let's import the required data
df = pd.read_csv(r'E:\Study\Projects\EDA\output_feature_engineerig_data.csv')
pd.set_option('display.max_columns', None)

In [3]:
# Since we have 0.2% of missing values of overall dataframe, we will drop it
#null_count = df.isnull().sum().sum()
#total_values = df.size
#percentage_missing = (null_count/total_values) * 100
#print(f"The total percent of missing values is {percentage_missing}")
df.dropna(inplace=True)

In [4]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontage_nan,MasVnrArea_nan,GarageYrBlt_nan
0,1,4.110874,3,4.189655,9.042040,1,1,0,1,1,0,0,15,2,1,3,5,7,5,5,5,0,0,9,9,2,5.283204,2,3,4,3,3,1,6,6.561031,4,0.0,150,6.753438,2,4,1,3,6.753438,854,0.0,7.444833,1,0.000000,2,1,3,0.693147,2,8,4,0,1,4,5.0,2,2,548,2,3,2,0.000000,4.127134,0.000000,0.0,0.0,0.0,0,4,2,0.0,2,2008,2,3,12.247699,0.0,0.0,0.0
1,2,3.044522,3,4.394449,9.169623,1,1,0,1,1,2,0,10,1,1,3,3,6,8,31,31,0,0,4,3,1,0.000000,1,3,2,3,3,4,4,6.886532,4,0.0,284,7.141245,2,4,1,3,7.141245,0,0.0,7.141245,0,0.693147,2,0,3,0.693147,1,6,4,1,3,4,31.0,2,2,460,2,3,2,5.700444,0.000000,0.000000,0.0,0.0,0.0,0,4,2,0.0,5,2007,2,3,12.109016,0.0,0.0,0.0
2,3,4.110874,3,4.234107,9.328212,1,1,1,1,1,0,0,15,2,1,3,5,7,5,7,6,0,0,9,9,2,5.093750,2,3,4,3,3,2,6,6.188264,4,0.0,434,6.825460,2,4,1,3,6.825460,866,0.0,7.488294,1,0.000000,2,1,3,0.693147,2,6,4,1,3,4,7.0,2,2,608,2,3,2,0.000000,3.761200,0.000000,0.0,0.0,0.0,0,4,2,0.0,9,2008,2,3,12.317171,0.0,0.0,0.0
3,4,4.262680,3,4.110874,9.164401,1,1,1,1,1,1,0,17,2,1,3,5,7,5,91,36,0,0,3,2,1,0.000000,1,3,1,2,4,1,4,5.379897,4,0.0,540,6.629363,2,3,1,3,6.869014,756,0.0,7.448916,1,0.000000,1,0,3,0.693147,2,7,4,1,4,2,8.0,1,3,642,2,3,2,0.000000,3.583519,5.609472,0.0,0.0,0.0,0,4,2,0.0,2,2006,2,1,11.849405,0.0,0.0,0.0
4,5,4.110874,3,4.442651,9.565284,1,1,1,1,1,2,0,21,2,1,3,5,8,5,8,8,0,0,9,9,2,5.860786,2,3,4,3,3,3,6,6.486161,4,0.0,490,7.044033,2,4,1,3,7.044033,1053,0.0,7.695758,1,0.000000,2,1,4,0.693147,2,9,4,1,3,4,8.0,2,3,836,2,3,2,5.262690,4.442651,0.000000,0.0,0.0,0.0,0,4,2,0.0,12,2008,2,3,12.429220,0.0,0.0,0.0

In [5]:
# We will now split the data into X_train and y_train to build the model.
# y_train will be the dependent variable vector(SalePrice)
y_train = df['SalePrice']

In [6]:
# Now since we don't need 'Id' and 'SalePrice' in X_train varaible, we will drop those 2 columns
X_train = df.drop(['Id', 'SalePrice'], axis=1)

In [33]:
# Now let's import the LASSO & SelectFromModel class to select the best required features for building model
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel
feature_selection = SelectFromModel(Lasso(alpha=0.01, random_state=11))
feature_selection.fit(X_train, y_train)

SelectFromModel(estimator=Lasso(alpha=0.01, random_state=11))

In [35]:
feature_selection.get_support()

array([ True, False, False,  True, False, False, False, False, False,
        True, False,  True, False, False, False,  True,  True,  True,
        True,  True, False, False,  True, False, False, False, False,
       False, False, False, False,  True, False,  True, False,  True,
        True, False, False,  True, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False, False,  True,  True,  True,  True, False,  True, False,
       False, False,  True,  True, False, False,  True, False, False,
       False, False, False, False, False, False,  True, False, False,
       False])

In [65]:
selected_features = X_train.columns[(feature_selection.get_support())]

print(f"The overall count of feature is {X_train.shape[1]}")
print(f"The unwanted features that are removed is {len(selected_features)}")
print(f"The no. of features that have zero coefficients {np.sum(feature_selection.estimator_.coef_ == 0)}")

The overall count of feature is 82
The unwanted features that are removed is 27
The no. of features that have zero coefficients 55

In [67]:
selected_features

Index(['MSSubClass', 'LotArea', 'LotConfig', 'Neighborhood', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'Exterior1st', 'BsmtExposure', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF',
       'HeatingQC', '1stFlrSF', '2ndFlrSF', 'TotRmsAbvGrd', 'FireplaceQu',
       'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'ScreenPorch', 'SaleCondition'],
      dtype='object')

In [69]:
X_train = X_train[selected_features]

In [73]:
X_train

,MSSubClass,LotArea,LotConfig,Neighborhood,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtExposure,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,HeatingQC,1stFlrSF,2ndFlrSF,TotRmsAbvGrd,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageArea,WoodDeckSF,OpenPorchSF,ScreenPorch,SaleCondition
0,4.110874,9.042040,0,15,5,7,5,5,5,9,1,6.561031,0.000000,150,4,6.753438,854,8,1,4,5.0,2,548,0.000000,4.127134,0.0,3
1,3.044522,9.169623,2,10,3,6,8,31,31,4,4,6.886532,0.000000,284,4,7.141245,0,6,3,4,31.0,2,460,5.700444,0.000000,0.0,3
2,4.110874,9.328212,0,15,5,7,5,7,6,9,2,6.188264,0.000000,434,4,6.825460,866,6,3,4,7.0,2,608,0.000000,3.761200,0.0,3
3,4.262680,9.164401,1,17,5,7,5,91,36,3,1,5.379897,0.000000,540,3,6.869014,756,7,4,2,8.0,1,642,0.000000,3.583519,0.0,1
4,4.110874,9.565284,2,21,5,8,5,8,8,9,3,6.486161,0.000000,490,4,7.044033,1053,9,3,4,8.0,2,836,5.262690,4.442651,0.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,4.110874,8.976894,0,12,5,6,5,8,7,9,1,0.000000,0.000000,953,4,6.860664,694,7,3,4,8.0,2,460,0.000000,3.713572,0.0,3
1456,3.044522,9.486152,0,13,3,6,6,32,22,8,1,6.673298,5.099866,589,2,7.637234,0,7,3,4,32.0,1,500,5.857933,0.000000,0.0,3
1457,4.262680,9.109746,0,17,5,7,9,69,4,10,1,5.620401,0.000000,877,4,7.080868,1152,9,4,4,69.0,2,252,0.000000,4.110874,0.0,3
1458,3.044522,9.181735,0,8,3,5,6,60,14,4,2,3.912023,6.937314,0,3,6.983790,0,5,1,4,60.0,1,240,5.905362,0.000000,0.0,3
1459,3.044522,9.204121,0,4,3,5,6,43,43,6,1,6.722630,5.673323,136,3,7.136483,0,6,1,4,43.0,3,276,6.602588,4.234107,0.0,3